### ISSUE TITLE
Sample of metadata of DocVQA

### ISSUE THREAD

**Issue by moni-learn010** [clovaai/donut#1]
Great Work. Could you please share the sample of ground truth part/meta data of the Document VQA? For example, in the ground truth(meta data) cord data, it has gt parse, meta, valid line and the valid line has each word along with quad information. I am curious about the ground truth part of the VQA data.  what will be the structure of the valid line? will it be full answer with the quad information? or it will be answer splitted into word along with quad information?

**Comment by gwkrsrch** [comment]
Hi, thank you for the first issue :)

We'll consider it, but let me get a quick answer first. Hope this answers your question.
As explained in the README, the dictionary contains either gt_parse or gt_parses. 

**Other fields (metadata) can be added to the dictionary but will not be used.**

Donut interprets all tasks as a JSON prediction problem. The only thing to do is preparing gt_parse or gt_parses for the task.
We simply converted the ground truth dataset into a format of `[{"question" : "what is the model name?", "answer" : "donut"}, {"question" : "what is the model name?", "answer" : "document understanding transformer"}]` to make the `gt_parses` for DocVQA task.

**Comment by moni-learn010** [comment]
Thanks for your explanation. Yes, it works now. Appreciate it.
