### ISSUE TITLE
Donut: Several images

### ISSUE THREAD

**Issue by Gabriel9753** [clovaai/donut#104]
Hello,
I have a question about an idea to implement an advanced use case using Donut.
Is it possible to include multiple documents in an inference? The idea is not to merge the images and put them into the model, but for example to infer several images one after the other and only after a certain number of images, decode the collected embeddings. So it would be possible to use Donut for multi-paging.
Is there a reasonable approach for this?
I would be very grateful for answers and ideas!

**Comment by llStringll** [comment]
I think you should be able to do that multiple encoders with shared weights, and all of the outputs of encoders go as inputs to decoder, as queries for attention, but you have to retrain the entire model from scratch. This one won't work cause we are adding extra dimensions in decoder input

**Comment by NielsRogge** [comment]
Yes indeed, you can encode each page using the vision encoder of Donut (or any other vision encoder), which will give you `last_hidden_states` (image patch embeddings) for each document. Next, you can concatenate those along the sequence dimension and use them as keys and values in the cross-attention operation with a text decoder. But indeed you would need to retrain the cross-attention layers again from scratch (you could use the parameters of all other layers of Donut's text decoder)

**Comment by Gabriel9753** [comment]
Thank you for the detailed answers! I will try it soon.

**Comment by pathikg** [comment]
> Yes indeed, you can encode each page using the vision encoder of Donut (or any other vision encoder), which will give you `last_hidden_states` (image patch embeddings) for each document. Next, you can concatenate those along the sequence dimension and use them as keys and values in the cross-attention operation with a text decoder. But indeed you would need to retrain the cross-attention layers again from scratch (you could use the parameters of all other layers of Donut's text decoder)

Approach which I am suggesting might not follow author's question but is it possible to create patch partition for multiple images separately then concatenate them and pass it to through our encoder blocks?
Since we are only modifying the input we do not need to retrain the model from scratch
