### ISSUE TITLE
Memory Required for training model?

### ISSUE THREAD

**Issue by vinaysingh8866** [clovaai/donut#111]
Hey, I'm trying to load the model on 3090ti keep on getting out of memory errors, is there a way to fine-tune it on 24GB of ram?

**Comment by TheSeriousProgrammer** [comment]
Kindly try performing a search in github issues with key words before submitting a new issue
Refer to this : https://github.com/clovaai/donut/issues/103
16gb GPU memory is the min requirements, one could go lower by modifying the training code

By 24gb memory are you talking about system RAM, cause that wont help in training , check your GPU's VRAM

**Comment by vinaysingh8866** [comment]
I checked the issues none of them helped me I'm running Ubuntu 20 I have 24GB of VRAM but it's still running out of memory.

**Comment by vinaysingh8866** [comment]
Reseting the env most likely a problem with that thanks for confirming 16GB.
