### ISSUE TITLE
Train donut to predict bounding boxes

### ISSUE THREAD

**Issue by Rabie-H** [clovaai/donut#114]
Is it possible to train donut to predict bounding bboxes by passing them as their coordinates as a list in the ground truth?

**Comment by logan-markewich** [comment]
This seems possible? See something like UDOP for reference: https://github.com/microsoft/i-Code/tree/main/i-Code-Doc

In my opinion though, if you need bounding boxes, just use tesseract (or a paid OCR service)

**Comment by Altimis** [comment]
Hi @logan-markewich. You mentioned using a "customized OCR". I would like to know how I could integrate a customized OCR engine (like Google's). IS it possible please ? Thank you
