### ISSUE TITLE
How to use the "previous text contexts" for pre-training phase?

### ISSUE THREAD

**Issue by yousefis** [clovaai/donut#127]
In the paper mentioned:

"In the pre-training phase, Donut learns how to read the texts by predicting the next words by conditioning jointly on the image and previous text contexts."

What I don't understand is that how the "previous text contexts" is used for the pretraining process while the input of the model is only an image. How I should change the fine-tuning code to be able to pretrain the model?

**Comment by sudhitpanchal** [comment]
Refer to Research paper you will get to know what works in backend.
