### ISSUE TITLE
About Paper Photos dataset

### ISSUE THREAD

**Issue by baopmessi** [clovaai/donut#13]
Thanks for great work! . Can you share paper photos datasets which you using for synthdog augmentation  , or I missing something.

**Comment by gwkrsrch** [comment]
Hi, thank you for your interest.
The SynthDoG samples are generated from publicly available sources. 
Details are available at https://arxiv.org/abs/2111.15664 (especially, Section 2.3 and Appendix A.2).

Hope this helps :) Please let me know if you are still confused.

**Comment by baopmessi** [comment]
Thanks for quick reply. I want to create my own dataset. But i need "Document Paper textures are sampled from the photos that we collected" in Appendix A.2 to can generate my text. I see https://github.com/clovaai/donut/tree/master/synthdog/resources/paper with 6 images. Are you using only those.

**Comment by gwkrsrch** [comment]
Yes, it is. Those images are cropped and used as paper textures (each image has a large size).
