### ISSUE TITLE
Image longer axis alignment issue

### ISSUE THREAD

**Issue by llStringll** [clovaai/donut#134]
https://github.com/clovaai/donut/blob/217cffb111a57ebce1025ff84a722a8d9914e05b/donut/model.py#L112
As per this line, the image will be rotated when it IS aligned with longer axis of canvas, instead, we should only rotate when longer axis of image does not align with longer axis of canvas.

Also here, https://github.com/clovaai/donut/blob/master/donut/model.py#L118 why are we resizing width as height and height as width?
```
        img.thumbnail((self.input_size[1], self.input_size[0]))
        delta_width = self.input_size[1] - img.width
        delta_height = self.input_size[0] - img.height
```
input_size[1] and input_size[0] are interchanged here, arn't they?

Thank you in advance for any clarifications.

**Comment by yonlas** [comment]
Hi, I currently have the same question, could you share why did you close your issue or if you got the answer? @llStringll 
Thanks

**Comment by VictorAtPL** [comment]
@llStringll @yonlas 

The provided code is correct.

`input_size` in config should be provided as `[height, width]` despite docstrings saying the opposite.

Then width is the second dimension (1 when 0-indexed) and height will be the first dimension (0 when 0-indexed).

Additionally, `thumbnail` is a method of `Pillow`: https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.thumbnail which expects a 2-tuple: (width, height).
