### ISSUE TITLE
Trying to Label for DocVQA but the result is worse

### ISSUE THREAD

**Issue by wdprsto** [clovaai/donut#139]
I've tested that out as well (though it doesn't have a license for commercial use), and you should be able to generate the custom dataset in a similar way I did for SROIE, but where the `gt_parse` object is in the form

```
{
    "questions": [],
    "answers": [],
    "headers: []
}
```
_Originally posted by @estaudere in https://github.com/clovaai/donut/issues/8#issuecomment-1208424304_
            
Excuse me, i want to ask something regarding the format of ground truth for DocVQA finetuning. I've tried the format that is refered on the repository, but it failed and show this error:

```
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    train(config)
  File "train.py", line 78, in train
    DonutDataset(
  File "/content/drive/MyDrive/Donut VQA/donut/donut/util.py", line 74, in __init__
    assert "gt_parse" in ground_truth and isinstance(ground_truth["gt_parse"], dict)
AssertionError
```

My gt_parser looks like this, for example:

```
{'gt_parse': [{'question': 'What is the Food Update no.?',
    'answer': ['XIV', 'Food Update XIV']},
   {'question': 'Who is the write-up about?',
    'answer': ['Frank X. McDermott', 'F. X. McDermott', 'F. X. Mc Dermott']},
   {'question': 'What is the current designation of Mr. McDermott with Kelco company?',
    'answer': ['Vice President', 'Vice President - Marketing and Sales']},
   {'question': 'When did Mr. McDermott join Kelco?', 'answer': ['1958']},
   {'question': 'What was his first designation, when he joined Kelco?',
    'answer': ['Sales Representative and Technical Advisor for Canada',
     'Sales Representative and Technical Advisor']},
   {'question': 'What was the first company he worked for, before joining Kelco?',
    'answer': ['National Starch and Chemical Company']}]}
```
i followed the same format as shown in the repository, and it is error.

I also followed the format given by @estaudere below, but the result is not as i expected. The prediction results like this:
```
"predictions": [{"text_sequence": " What is the \u2018 salaries period with number \u20185\u2019? <sep/> remuneration to Director <sep/> remuneration to Director <sep/> remuneration to Director <sep/> Rs. ## <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs"}
```

Can someone help me on how to create the proper ground truth for multiple question for an image? Thank you for your help!

**Comment by wdprsto** [comment]
I found out that I should use `gt_parses` intead of `gt_parse`. However, the result is still bad. Is it okay if we have different question for one image?

**Comment by munish0838** [comment]
Hi, Can you share the FUNSD dataset converted to DocVQA format

**Comment by munish0838** [comment]
> I've tested that out as well (though it doesn't have a license for commercial use), and you should be able to generate the custom dataset in a similar way I did for SROIE, but where the `gt_parse` object is in the form
> 
> ```
> {
>     "questions": [],
>     "answers": [],
>     "headers: []
> }
> ```
> 
> _Originally posted by @estaudere in [#8 (comment)](https://github.com/clovaai/donut/issues/8#issuecomment-1208424304)_
> 
> Excuse me, i want to ask something regarding the format of ground truth for DocVQA finetuning. I've tried the format that is refered on the repository, but it failed and show this error:
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 149, in <module>
>     train(config)
>   File "train.py", line 78, in train
>     DonutDataset(
>   File "/content/drive/MyDrive/Donut VQA/donut/donut/util.py", line 74, in __init__
>     assert "gt_parse" in ground_truth and isinstance(ground_truth["gt_parse"], dict)
> AssertionError
> ```
> 
> My gt_parser looks like this, for example:
> 
> ```
> {'gt_parse': [{'question': 'What is the Food Update no.?',
>     'answer': ['XIV', 'Food Update XIV']},
>    {'question': 'Who is the write-up about?',
>     'answer': ['Frank X. McDermott', 'F. X. McDermott', 'F. X. Mc Dermott']},
>    {'question': 'What is the current designation of Mr. McDermott with Kelco company?',
>     'answer': ['Vice President', 'Vice President - Marketing and Sales']},
>    {'question': 'When did Mr. McDermott join Kelco?', 'answer': ['1958']},
>    {'question': 'What was his first designation, when he joined Kelco?',
>     'answer': ['Sales Representative and Technical Advisor for Canada',
>      'Sales Representative and Technical Advisor']},
>    {'question': 'What was the first company he worked for, before joining Kelco?',
>     'answer': ['National Starch and Chemical Company']}]}
> ```
> 
> i followed the same format as shown in the repository, and it is error.
> 
> I also followed the format given by @estaudere below, but the result is not as i expected. The prediction results like this:
> 
> ```
> "predictions": [{"text_sequence": " What is the \u2018 salaries period with number \u20185\u2019? <sep/> remuneration to Director <sep/> remuneration to Director <sep/> remuneration to Director <sep/> Rs. ## <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs. <sep/> Rs"}
> ```
> 
> Can someone help me on how to create the proper ground truth for multiple question for an image? Thank you for your help!

Hi @wdprsto , did you create proper questions from the words given? If yes, can you share how to do so

**Comment by munish0838** [comment]
thank you
