### ISSUE TITLE
How to perform text reading task

### ISSUE THREAD

**Issue by mike132129** [clovaai/donut#14]
Hi, thanks for the great project!
I am exciting to integrate the model into my document understanding project, and I want to implement text reading task.
I have one question:

- According to my understanding, i should download the pretrained model from "naver-clova-ix/donut-base", but what would be the prompt word that fed into decoder?

**Comment by gwkrsrch** [comment]
Hi, the current codebase uses each dataset name as a task start token by default (or you can manually specify the task start token). The following lines are related to this:
- https://github.com/clovaai/donut/blob/1.0.5/train.py#L63
- https://github.com/clovaai/donut/blob/1.0.5/train.py#L84-L85

You can check the task start tokens of "naver-clova-ix/donut-base" from [donut-base/added_tokens.json](https://huggingface.co/naver-clova-ix/donut-base/blob/official/added_tokens.json). If you have a scanned English document, "<s_iitcdip>" will work as the prompt.

Hope this helps :) Please let me know if you are still confused.
