### ISSUE TITLE
Donut Custom Model Training 

### ISSUE THREAD

**Issue by rajsaraiya009** [clovaai/donut#149]
Hello I did Tried to Train and fine tune model based on my own dataset and I want to receive fields like address and date. But why am i not getting entity name in the output rather than that i get output like below if anyone can help me it will be great thanks. 
So below you can see i am getting like "text sequence" rather than address as entity. 
**Output:** 
{'predictions': [{'text_sequence': '18,SS 22/2 DANAGER AYA 4400 SELANGOR </s_ADDRESS>'}]}

**Comment by YAOYI626** [comment]
what's your ground-truth looks like? is that the same format with what you're showing?

**Comment by kushal-h** [comment]
> Hello I did Tried to Train and fine tune model based on my own dataset and I want to receive fields like address and date. But why am i not getting entity name in the output rather than that i get output like below if anyone can help me it will be great thanks. So below you can see i am getting like "text sequence" rather than address as entity. **Output:** {'predictions': [{'text_sequence': '18,SS 22/2 DANAGER AYA 4400 SELANGOR </s_ADDRESS>'}]}

Hi,

I wanted to train this for my own dataset. I wanted to know how did you train the model. Please provide me some documentation that you followed. 

Thanks in advance.

**Comment by rajsaraiya009** [comment]
@YAOYI626 I solved the issue. While doing inference you need to provide the data set name on which you trained the model than it will identify the entity. Thanks for the response.

**Comment by rajsaraiya009** [comment]
@kushal-h you can read the readme file clearly all steps are mentioned or else you can visit link below 
https://towardsdatascience.com/ocr-free-document-understanding-with-donut-1acfbdf099be
https://towardsdatascience.com/fine-tuning-ocr-free-donut-model-for-invoice-recognition-46e22dc5cff1

note:  I have created my own data-set the links above will help you in understanding the training of the model.
