### ISSUE TITLE
test.py seems broken

### ISSUE THREAD

**Issue by maxjeblick** [clovaai/donut#15]
In `test.py`, f-string formatting with double-quotation marks of `ground_truth["gt_parses"][0]['question'].lower`
causes some parsing issues:
![test](https://user-images.githubusercontent.com/24281881/183511488-73b53aa0-9e43-4508-837a-ceda3b3c768a.png)

Extracting the question prompt, i.e.
```
        if args.task_name == "docvqa":
            question = ground_truth["gt_parses"][0]['question'].lower()
            output = pretrained_model.inference(
                image=sample["image"],
                prompt=f"<s_{args.task_name}><s_question>{question}</s_question><s_answer>",
            )["predictions"][0]
```
solves the issue.

**Comment by gwkrsrch** [comment]
Hi, 787d918 would probably solve the issue. Thank you for the report!  :)
