### ISSUE TITLE
how to prepare zhtrainticket?

### ISSUE THREAD

**Issue by chentianyangWHU** [clovaai/donut#150]
Hi, thank you for you awesome work! 
You mentioned "it should be prepared from https://github.com/beacandler/EATEN" in config/train_zhtrainticket.yaml, and I want to know how to do that? Specifically, how to organize the file structure of zhtrainticket in my computer, so that the function 'load_dataset' in donut/util.py would load that dataset correctly? Or could you please give a diagram of the file tree?
Thanks a lot!

**Comment by Forrest-ht** [comment]
same question

**Comment by logan-markewich** [comment]
I haven't trained on that specific dataset, but I have trained a few donut models.

I just changed the code in `donut/util.py` to load data from my own jsonl file

As you can see, it expects each sample to be a json object. So if you have a file where each line is a json object, you are good to go 

![image](https://user-images.githubusercontent.com/22285038/221000418-209053d0-ca11-4fb9-843d-f4aaa03206e7.png)

**Comment by chentianyangWHU** [comment]
> I haven't trained on that specific dataset, but I have trained a few donut models.
> 
> I just changed the code in `donut/util.py` to load data from my own jsonl file, following the format in the readme
> 
> As you can see, it expects each sample to be a json object. So if you have a file where each line is a json object, you are good to go. Then you just need a single train and single test file (as well as the correct paths to all your images)
> 
> ![image](https://user-images.githubusercontent.com/22285038/221000418-209053d0-ca11-4fb9-843d-f4aaa03206e7.png)

thank you, I solved the problem.

**Comment by chentianyangWHU** [comment]
> same question

write a new dataload function to replace the default function "load_dataset" and return "dataset" with the same structure as what "load_dataset" returns.
