### ISSUE TITLE
artifacts.ckpt

### ISSUE THREAD

**Issue by Wyzix33** [clovaai/donut#151]
Hi, after fine-tunning i get a 2GB file artifacts.ckpt, do I need to upload it to huggingface or i can use the model without it?
Thanks

**Comment by chentianyangWHU** [comment]
same question. Do you figure out what artifacts.ckpt is? Thank you!

**Comment by Wyzix33** [comment]
Not yet...

**Comment by BakingBrains** [comment]
You can use it without artifacts.ckpt

**Comment by Wyzix33** [comment]
Thanks
