### ISSUE TITLE
Why delete state_dict in CustomCheckpointIO

### ISSUE THREAD

**Issue by YAOYI626** [clovaai/donut#157]
Thanks guys for your great great work. I have a question about the design of CustomCheckpointIO.

```python
class CustomCheckpointIO(CheckpointIO):
    def save_checkpoint(self, checkpoint, path, storage_options=None):
        del checkpoint["state_dict"]
        torch.save(checkpoint, path)
```

Why does it delete the `state_dict`, which usually contains model weights?  I did not found code to explicitly save the `pytorch_model.bin`. How are the weights inside `state_dict` saved?

Could you help me to understand these designs?

**Comment by gwkrsrch** [comment]
Hi @YAOYI626, DonutModelPLModule saves model weights in a format that is friendly with Huggingface's transformers. You can find the code block for this feature at (https://github.com/clovaai/donut/blob/1.0.9/lightning_module.py#L146-L150). I hope this information is helpful to you. Best.

**Comment by Vadkoz** [comment]
@YAOYI626 can you give advice on how to load weights from .ckpt files?
