### ISSUE TITLE
Which 4 MBartDecoderLayers Are Used?

### ISSUE THREAD

**Issue by htcml** [clovaai/donut#168]
I compared donut-base with asian-bart-ecjk. Donut-base has 4 MBartDecoderLayers while asian-bart-ecjk has 12 MBartDecoderLayers. Does donut-base use the weights from the first 4 MBartDecoderLayers of asian-bart-ecjk?

**Comment by gwkrsrch** [comment]
Hi @htcml, the decoder part of donut-base is initialized with the weights from the first 4 MBartDecoderLayers. And the model was trained with IIT-CDIP and SynthDoG. I hope this answer helps :)
