### ISSUE TITLE
How to calculate field-level F1 score of CORD test set

### ISSUE THREAD

**Issue by Veason-silverbullet** [clovaai/donut#17]
Hi, @gwkrsrch ,

DONUT is an excellent work for VDU community! We can reproduce the tree-based edit-distance results on the CORD test set. But it is tricky to calculate the field-level F1 score based on the tree-based prediction. Could you please explain how to calculate F1 of CORD test set? 

Many thanks for your effort!

**Comment by gwkrsrch** [comment]
Hi @Veason-silverbullet ,

we calculated micro-averaged field-level F1 accuracy score based on the tree-based prediction. `donut-python>=1.0.6` will support the F1 related functions.
- https://github.com/clovaai/donut/releases/tag/1.0.6

```
pip install donut-python --upgrade
```

See https://github.com/clovaai/donut#test also. Hope this helps :)
```
python test.py --dataset_name_or_path naver-clova-ix/cord-v2 --pretrained_model_name_or_path naver-clova-ix/donut-base-finetuned-cord-v2
100%|█████████████| 100/100 [00:37<00:00,  2.67it/s]
Total number of samples: 100, Tree Edit Distance (TED) based accuracy score: 0.9388447875172169, F1 accuracy score: 0.9155107187894073
```

**Comment by gwkrsrch** [comment]
Hi @Veason-silverbullet , there was an update to the functions. Please use `donut-python>=1.0.7` :)
