### ISSUE TITLE
Are "valid_line" and "meta" keys required for training?

### ISSUE THREAD

**Issue by finnthedawg** [clovaai/donut#18]
I noticed in the cordv2 dataset there is "valid_line", "meta", and other keys in the jsonl dictionary. 
Are these used/required during training for document parsing, or are they ignored by the system as it is not strictly gt_parse?

**Comment by gwkrsrch** [comment]
Other fields can be added to the dictionary but will not be used. #1 would be helpful to you.
Please let me know if you are still confused :)
