### ISSUE TITLE
Blurred CORD data in fine-tuning?

### ISSUE THREAD

**Issue by Hegelim** [clovaai/donut#198]
I noticed that the CORD data used in fine-tuning here: https://drive.google.com/drive/folders/17ZK7OulhAg0Lz9w4lT19kXKX9zeeDjAw
are blurred on the top (prob due to privacy concerns). I am just wondering are those blurred before fine-tuning or after fine-tuning? I tested some real world receipts without blurring and seems the results are not good

**Comment by thinh-huynh-re** [comment]
I'm sure that the receipts are blurred before fine-tuning
