### ISSUE TITLE
Fine-tuning on Apple M1/M2

### ISSUE THREAD

**Issue by abaranovskis-redsamurai** [clovaai/donut#225]
Hello,

Anyone tried finetuning Donut on Apple M1/M2. How does it compare to Nvidia GPU?

Thanks,
Andrej

**Comment by DoctorSlimm** [comment]
bump

**Comment by ewfian** [comment]
very slow, 10 images using 50 min

**Comment by abaranovskis-redsamurai** [comment]
> very slow, 10 images using 50 min

thanks.
