### ISSUE TITLE
How to serve trained donut model

### ISSUE THREAD

**Issue by Codedrainer** [clovaai/donut#228]
Hello,

I have successfully trained a Donut model using donut-base, and now I am looking for guidance on how to deploy the model for easy inference. I have already explored TorchServe and Hugging Face's documentation, but I couldn't find a straightforward solution.

Here are the files I have after training the model:

added_tokens.json
config.json
pytorch_model.bin
sentencepiece.bpe.model
special_tokens_map.json
tokenizer_config.json
I have been able to perform inference locally, but I need help with the steps to serve the model so that I can easily perform inference remotely.

Any assistance or guidance would be highly appreciated. Thank you!

**Comment by carlos21** [comment]
@Codedrainer how did you manage to generate those files?
added_tokens.json
config.json
pytorch_model.bin
sentencepiece.bpe.model
special_tokens_map.json
tokenizer_config.json

**Comment by Codedrainer** [comment]
@carlos21 i have used Donut to train a model and got these files, Finally, I made it to deployment.
