### ISSUE TITLE
How to estimate the required video memory?

### ISSUE THREAD

**Issue by chopin1998** [clovaai/donut#238]
when i adjust processor.image_processor.size  from {'height': 960, 'width': 720} to higher,  GPU said CUDA out of memory..

my Video Card 8GB video, i wanna know, if i wanna use {'height': 2560, 'width': 1920}, how much VRAM will be used? does 16GB ok ?

**Comment by sudhitpanchal** [comment]
More input size means more GPU, keep in mind that batch size and other parameters affect the same so as per your requirement 16 GB would be enough i guess what happened when you tried using 16GB?
