### ISSUE TITLE
Texts in "swenglish"?

### ISSUE THREAD

**Issue by henkish** [clovaai/donut#247]
Hello!

I have trained a model for parsing invoices (trained on private data set).
The model understands the structure of the documents very well!

But I have an issue with texts. It seems model detect correct text (in the document structure), but changes some words to some combination of Swedish-english or Swedish-german versions of the words. Or made up Swedish words.

The problem with the invoices is that texts also can contain product abbreviations, technical terms, etc. - and not always regular Swedish sentences. 

Is there some way to get more accurate texts?

Thanks in advance
Henrik

**Comment by henkish** [comment]
Training on additional documents, and more epochs seemed to improve results - but we still get some strange texts sometimes.

**Comment by Mohtadrao** [comment]
I get strange result all the time. Kindly tell me what to do? @henkish
