### ISSUE TITLE
For (Psuedo) Text Reading Task

### ISSUE THREAD

**Issue by PSanni** [clovaai/donut#25]
Hi for text reading task it instructs that: 

`You can use our SynthDoG 🐶 to generate synthetic images for the text reading task with proper gt_parse. See ./synthdog/README.md for details.`

But there is no detail over there for it.

**Comment by logan-markewich** [comment]
What details are you looking for? There is a readme there with an explanation on running synthdog

**Comment by PSanni** [comment]
how yo generate data in (Psuedo) Text Reading format ?

**Comment by gwkrsrch** [comment]
Hi, thanks to @logan-markewich for the comment :) Now I see the issue. 
All you need is just to follow the README. 
If you enter the command (`synthtiger -o {dataset_path} ... {config_path}`) as written in the README (https://github.com/clovaai/donut/tree/master/synthdog#usage), you will get a dataset in the desired format (that can be used for the psuedo text reading task).
Hope this helps. Please let me know if you are still confused.
