### ISSUE TITLE
Can donut support batch inference?

### ISSUE THREAD

**Issue by sjtu-cz** [clovaai/donut#262]
Can donut support batch inference?

**Comment by CheungZeeCn** [comment]
Why not? However, It's better to keep your batch prompt in the same length when inferring.

**Comment by sjtu-cz** [comment]
您好，你的邮件我已经收到~

**Comment by sjtu-cz** [comment]
> Why not? However, It's better to keep your batch prompt in the same length when inferring.

thanks
