### ISSUE TITLE
model checkpoint did not match

### ISSUE THREAD

**Issue by sglee487** [clovaai/donut#27]
I got error 
"Some weights of DonutModel were not initialized from the model checkpoint at naver-clova-ix/donut-base and are newly initialized because the shapes did not match"
when using training code in README.md.

may be some layer's shape does not match.

![image](https://user-images.githubusercontent.com/33611003/185062819-a72feb42-f9d9-446b-861f-293d860af043.png)
![image](https://user-images.githubusercontent.com/33611003/185062220-9aa6c209-9962-4a6d-a98f-e215a7554c85.png)

Is it not a serious problem?

**Comment by gwkrsrch** [comment]
No, it is not a serious problem :) It occurs when the model's input size is adjusted. Although some weights are newly initialized, the model training will be okay. 
Hope this helps. Please let me know if you are still confused.

**Comment by gwkrsrch** [comment]
8997ed5 will help to prevent such misunderstanding. Thanks again for the report :)

**Comment by sglee487** [comment]
Thank you for your explanation!
