### ISSUE TITLE
How much gpu memory size does single 1280,960 size photo need

### ISSUE THREAD

**Issue by Mrharry1997** [clovaai/donut#28]
I tried to run donut-base in 2080ti, batch set is 1. But it didn't work, and it looked like it's because the small gpu memory.
So I want to ask has anyone try to run it on 2080ti or how much gpu memory size does single 1280,960 size photo need

**Comment by TheSeriousProgrammer** [comment]
I was able to run the 1280x960  in a 16gb GPU t4 system , so may be you can try running it in cpu? or colab

**Comment by maycuatroi** [comment]
It takes 10-12GB of GPU RAM to train with an image size of 1280x960 and a batch size of 1.
Here is my log when training the model
![image](https://user-images.githubusercontent.com/5876946/187742478-2006c33c-ebb1-4281-9ef1-57c9ec2fc70f.png)

**Comment by gwkrsrch** [comment]
Close this issue since it seems to be resolved :)
Feel free to reopen this or open another issue if you have anything new for sharing or debugging.
