### ISSUE TITLE
Problem Finetuning with Provided Pretrained Model

### ISSUE THREAD

**Issue by xingjianz** [clovaai/donut#29]
Hi, I am encountering the following errors recently when I try to finetune using the provided pretrained models. 
1. When I cloned the original repo and tried finetuning on CORD per the instructions like below:
 `python train.py --config config/train_cord.yaml \
                --pretrained_model_name_or_path "naver-clova-ix/donut-base" \
                --dataset_name_or_paths '["naver-clova-ix/cord-v2"]' \
                --exp_version "test_experiment"   `
the following error pops up: 
`Traceback (most recent call last):
  File "train.py", line 149, in <module>
    train(config)
  File "train.py", line 130, in train
    callbacks=[lr_callback, checkpoint_callback],
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/argparse.py", line 345, in insert_env_defaults
    return fn(self, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 459, in __init__
    training_epoch_loop = TrainingEpochLoop(min_steps=min_steps, max_steps=max_steps)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 51, in __init__
    if max_steps < -1:
TypeError: '<' not supported between instances of 'NoneType' and 'int'`

2. When I tried with my local modified repo, the following error pops up
` Traceback (most recent call last):
  File "train.py", line 146, in <module>
    train(config)
  File "train.py", line 57, in train
    model_module = DonutModelPLModule(config)
  File "/data/project/users/xingjianzhao/visual-information-extraction/code/Donut/donut/donut/lightning_module.py", line 94, in __init__
    self.model = DonutModel.from_pretrained(
  File "/data/project/users/xingjianzhao/visual-information-extraction/code/Donut/donut/donut/donut/model.py", line 642, in from_pretrained
    model = super(DonutModel, cls).from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 2155, in from_pretrained
    model, missing_keys, unexpected_keys, mismatched_keys, error_msgs = cls._load_pretrained_model(
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 2282, in _load_pretrained_model
    model._init_weights(module)
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 1050, in _init_weights
    raise NotImplementedError(f"Make sure `_init_weights` is implemented for {self.__class__}")
NotImplementedError: Make sure `_init_weights` is implemented for <class 'donut.model.DonutModel'>
`
While I did made some modifications, I tried with previous versions of my repo that worked perfectly fine and this error still pops up. However when I use my previous finetuned models (trained with the exact same code), it works fine. I'm wondering if you may have an idea on what the problems could be. Thanks!

**Comment by PSanni** [comment]
Did you cloned the repo or installed using PIP ? 
For your (1) question replacing `max_steps: null`  with `max_steps: -1` in ### *.config file should solve the issue.

**Comment by xingjianz** [comment]
Thanks! I cloned the repo, and after some slight modifications successfully finetuned on the SROIE dataset before, but a couple days ago when I tried again, the error shown in the second question popped up.

**Comment by leitouran** [comment]
I'm having the same problem as described in (2). Since I'm working on SageMaker under very restrictive VPC constraints, I can only pre-download checkpoints and datasets. I cloned the repo and installed with `pip install -e .`. After that, I uploaded the predownloaded `CORD `dataset and `donut-base` model and placed them inside repo folder.

```bash
$> tree donut/
donut/
├── LICENSE
├── NOTICE
├── README.md
├── app.py
├── config
│   ├── train_cord.yaml
│   ├── train_docvqa.yaml
│   ├── train_rvlcdip.yaml
│   └── train_zhtrainticket.yaml
├── dataset
│   ├── cord-v2
│   │   ├── README.md
│   │   ├── data
│   │   │   ├── test-00000-of-00001-9c204eb3f4e11791.parquet
│   │   │   ├── train-00000-of-00004-b4aaeceff1d90ecb.parquet
│   │   │   ├── train-00001-of-00004-7dbbe248962764c5.parquet
│   │   │   ├── train-00002-of-00004-688fe1305a55e5cc.parquet
│   │   │   ├── train-00003-of-00004-2d0cd200555ed7fd.parquet
│   │   │   └── validation-00000-of-00001-cc3c5779fe22e8ca.parquet
│   │   └── dataset_infos.json
│   └── cord-v2.zip
├── donut
│   ├── __init__.py
│   ├── _version.py
│   ├── model.py
│   └── util.py
├── donut_python.egg-info
│   ├── PKG-INFO
│   ├── SOURCES.txt
│   ├── dependency_links.txt
│   ├── requires.txt
│   └── top_level.txt
├── lightning_module.py
├── misc
│   ├── overview.png
│   ├── sample_image_cord_test_receipt_00004.png
│   ├── sample_image_donut_document.png
│   ├── sample_synthdog.png
│   └── screenshot_gradio_demos.png
├── models
│   ├── donut-base
│   │   ├── README.md
│   │   ├── added_tokens.json
│   │   ├── config.json
│   │   ├── preprocessor_config.json
│   │   ├── pytorch_model.bin
│   │   ├── sentencepiece.bpe.model
│   │   ├── special_tokens_map.json
│   │   ├── tokenizer.json
│   │   └── tokenizer_config.json
│   └── donut-base.zip
├── result
│   └── train_cord
│       └── test_experiment
│           └── config.yaml
├── setup.py
├── synthdog
│   ├── README.md
│   ├── config_en.yaml
│   ├── config_ja.yaml
│   ├── config_ko.yaml
│   ├── config_zh.yaml
│   ├── elements
│   │   ├── __init__.py
│   │   ├── background.py
│   │   ├── content.py
│   │   ├── document.py
│   │   ├── paper.py
│   │   └── textbox.py
│   ├── layouts
│   │   ├── __init__.py
│   │   ├── grid.py
│   │   └── grid_stack.py
│   ├── resources
│   │   ├── background
│   │   │   ├── bedroom_83.jpg
│   │   │   ├── bob+dylan_83.jpg
│   │   │   ├── coffee_122.jpg
│   │   │   ├── coffee_18.jpeg
│   │   │   ├── crater_141.jpg
│   │   │   ├── cream_124.jpg
│   │   │   ├── eagle_110.jpg
│   │   │   ├── farm_25.jpg
│   │   │   └── hiking_18.jpg
│   │   ├── corpus
│   │   │   ├── enwiki.txt
│   │   │   ├── jawiki.txt
│   │   │   ├── kowiki.txt
│   │   │   └── zhwiki.txt
│   │   ├── font
│   │   │   ├── en
│   │   │   │   ├── NotoSans-Regular.ttf
│   │   │   │   └── NotoSerif-Regular.ttf
│   │   │   ├── ja
│   │   │   │   ├── NotoSansJP-Regular.otf
│   │   │   │   └── NotoSerifJP-Regular.otf
│   │   │   ├── ko
│   │   │   │   ├── NotoSansKR-Regular.otf
│   │   │   │   └── NotoSerifKR-Regular.otf
│   │   │   └── zh
│   │   │       ├── NotoSansSC-Regular.otf
│   │   │       └── NotoSerifSC-Regular.otf
│   │   └── paper
│   │       ├── paper_1.jpg
│   │       ├── paper_2.jpg
│   │       ├── paper_3.jpg
│   │       ├── paper_4.jpg
│   │       ├── paper_5.jpg
│   │       └── paper_6.jpg
│   ├── template.py
│   └── utils
│       ├── __init__.py
│       └── text_reader.py
├── test.py
└── train.py
```

Then, from the terminal:

```
root@pytorch-1-10-gpu-py-ml-g4dn-xlarge-53638dc8bb3d40f5ed7ac21aaf03:~/keyval_extraction/donut# python train.py --config config/train_cord.yaml \
>                 --pretrained_model_name_or_path "models/donut-base" \
>                 --dataset_name_or_paths "dataset/cord-v2" \
>                 --exp_version "test_experiment"
/opt/conda/lib/python3.8/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
resume_from_checkpoint_path: None
result_path: ./result
pretrained_model_name_or_path: models/donut-base
dataset_name_or_paths: dataset/cord-v2
sort_json_key: False
train_batch_sizes: 
  - 8
val_batch_sizes: 
  - 1
input_size: 
  - 1280
  - 960
max_length: 768
align_long_axis: False
num_nodes: 1
seed: 2022
lr: 3e-05
warmup_steps: 300
num_training_samples_per_epoch: 800
max_epochs: 30
max_steps: -1
num_workers: 8
val_check_interval: 1.0
check_val_every_n_epoch: 3
gradient_clip_val: 1.0
verbose: True
exp_name: train_cord
exp_version: test_experiment
Config is saved at result/train_cord/test_experiment/config.yaml
Global seed set to 2022
You are using a model of type vision-encoder-decoder to instantiate a model of type donut. This is not supported for all configurations of models and can yield errors.
/opt/conda/lib/python3.8/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /codebuild/output/src741569495/src/aten/src/ATen/native/TensorShape.cpp:2156.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "train.py", line 149, in <module>
    train(config)
  File "train.py", line 57, in train
    model_module = DonutModelPLModule(config)
  File "/root/keyval_extraction/donut/lightning_module.py", line 30, in __init__
    self.model = DonutModel.from_pretrained(
  File "/root/keyval_extraction/donut/donut/model.py", line 595, in from_pretrained
    model = super(DonutModel, cls).from_pretrained(pretrained_model_name_or_path, revision="official", *model_args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2155, in from_pretrained
    model, missing_keys, unexpected_keys, mismatched_keys, error_msgs = cls._load_pretrained_model(
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2282, in _load_pretrained_model
    model._init_weights(module)
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1050, in _init_weights
    raise NotImplementedError(f"Make sure `_init_weights` is implemented for {self.__class__}")
NotImplementedError: Make sure `_init_weights` is implemented for <class 'donut.model.DonutModel'>
```

Here's my environment

```
absl-py==1.2.0
aiohttp==3.8.1
aiosignal==1.2.0
apex==0.1
asttokens==2.0.5
async-timeout==4.0.2
attrs==20.3.0
awscli==1.22.68
awsio @ https://aws-s3-plugin.s3.us-west-2.amazonaws.com/binaries/0.0.1/1c3e69e/awsio-0.0.1-cp38-cp38-manylinux1_x86_64.whl
backcall==0.2.0
bcrypt==3.2.0
black==22.1.0
bokeh==2.4.2
boto3==1.21.13
botocore==1.24.13
Bottleneck==1.3.2
brotlipy==0.7.0
cachetools==5.2.0
certifi==2021.10.8
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1625835293160/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click==8.0.4
cloudpickle==2.0.0
cmake==3.18.2.post1
colorama==0.4.3
conda==4.11.0
conda-content-trust @ file:///tmp/build/80754af9/conda-content-trust_1617045594566/work
conda-package-handling @ file:///home/conda/feedstock_root/build_artifacts/conda-package-handling_1618231394280/work
cryptography==36.0.1
cycler==0.11.0
Cython @ file:///tmp/build/80754af9/cython_1594831566883/work
datasets==2.4.0
decorator==5.1.1
dill==0.3.4
docutils==0.15.2
-e git+https://github.com/clovaai/donut.git@8997ed5cc7c73069e55138255cfb3a06b3011815#egg=donut_python
executing==0.8.3
filelock==3.8.0
fonttools==4.29.1
frozenlist==1.3.1
fsspec==2022.2.0
future==0.18.2
gevent==21.12.0
google-auth==2.10.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
greenlet==1.1.2
grpcio==1.47.0
h5py @ file:///tmp/build/80754af9/h5py_1637138879700/work
horovod==0.21.3
huggingface-hub==0.8.1
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
imageio==2.16.1
importlib-metadata==4.11.2
inotify-simple==1.2.1
ipykernel==5.5.6
ipython==8.0.1
ipython-genutils==0.2.0
jedi==0.18.1
Jinja2==3.0.3
jmespath==0.10.0
joblib @ file:///tmp/build/80754af9/joblib_1635411271373/work
jsonpatch==1.32
jsonpointer==2.2
jupyter-client==6.1.5
jupyter-core==4.9.2
kiwisolver==1.3.2
llvmlite==0.36.0
Markdown==3.4.1
MarkupSafe==2.1.0
matplotlib==3.5.1
matplotlib-inline==0.1.3
mpi4py==3.0.3
multidict==6.0.2
multiprocess==0.70.12.2
munch==2.5.0
mypy-extensions==0.4.3
nltk==3.7
numba==0.53.1
numexpr @ file:///tmp/build/80754af9/numexpr_1640704205910/work
numpy==1.22.2
oauthlib==3.2.0
opencv-python==4.5.5.62
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
pandas==1.4.1
paramiko==2.9.2
parso==0.8.3
pathos==0.2.8
pathspec==0.9.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.1
platformdirs==2.5.1
plotly==5.6.0
pox==0.3.0
ppft==1.6.6.4
prompt-toolkit==3.0.30
protobuf==3.19.4
protobuf3-to-dict==0.1.5
psutil==5.9.0
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==7.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybind11==2.9.1
pycosat @ file:///home/conda/feedstock_root/build_artifacts/pycosat_1610094800877/work
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pyDeprecate==0.3.2
pyfunctional==1.4.3
Pygments==2.12.0
pyinstrument==3.4.2
pyinstrument-cext==0.2.4
PyNaCl==1.5.0
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1594392929924/work
pyparsing==3.0.7
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1635862404924/work
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
pytorch-lightning==1.7.2
pytz==2021.3
PyYAML==5.4.1
pyzmq==22.3.0
regex==2022.8.17
requests @ file:///opt/conda/conda-bld/requests_1641824580448/work
requests-oauthlib==1.3.1
responses==0.18.0
retrying==1.3.3
rsa==4.7.2
ruamel-yaml-conda @ file:///tmp/build/80754af9/ruamel_yaml_1616016699510/work
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
s3fs==0.4.2
s3transfer==0.5.2
sagemaker==2.77.1
sagemaker-experiments==0.1.35
sagemaker-pytorch-training==2.4.0
sagemaker-training==4.0.1
scikit-learn @ file:///tmp/build/80754af9/scikit-learn_1642617107864/work
scipy==1.8.0
sconf==0.2.5
seaborn==0.11.2
sentencepiece==0.1.97
shap==0.40.0
six @ file:///tmp/build/80754af9/six_1623709665295/work
sklearn==0.0
slicer==0.0.7
smclarify==0.2
smdebug==1.0.13b20220304
smdebug-rulesconfig==1.0.1
smdistributed-dataparallel @ https://smdataparallel.s3.amazonaws.com/binary/pytorch/1.10.2/cu113/2022-02-18/smdistributed_dataparallel-1.4.0-cp38-cp38-linux_x86_64.whl
smdistributed-modelparallel @ https://sagemaker-distributed-model-parallel.s3.us-west-2.amazonaws.com/pytorch-1.10.0/build-artifacts/2022-02-21-19-26/smdistributed_modelparallel-1.7.0-cp38-cp38-linux_x86_64.whl
stack-data==0.2.0
tabulate==0.8.9
tenacity==8.0.1
tensorboard==2.10.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
threadpoolctl @ file:///Users/ktietz/demo/mc3/conda-bld/threadpoolctl_1629802263681/work
timm==0.6.7
tokenizers==0.12.1
tomli==2.0.1
torch @ https://aws-pytorch-cicd-v3-binaries.s3.us-west-2.amazonaws.com/r1.10.2_aws_v3/20220209-025350/bea1183a47174ef43ab9874c643357fa77755932/gpu/torch-1.10.2%2Bcu113-cp38-cp38-manylinux1_x86_64.whl
torchfile==0.1.0
torchmetrics==0.9.3
torchnet==0.0.4
torchvision @ https://framework-binaries.s3.us-west-2.amazonaws.com/pytorch/1.10.2/torchvision-0.11.3-cp38-cp38-linux_x86_64.whl
tornado==6.1
tqdm @ file:///tmp/build/80754af9/tqdm_1635330843403/work
traitlets==5.1.1
transformers==4.21.1
typing_extensions==4.1.1
urllib3==1.26.7
visdom==0.1.8.9
wcwidth==0.2.5
websocket-client==1.3.1
Werkzeug==2.0.3
xxhash==3.0.0
yarl==1.8.1
zipp==3.7.0
zope.event==4.5.0
zope.interface==5.4.0
zss==1.2.0
```
Any ideas of what might be going on?

**Comment by gwkrsrch** [comment]
Hi @leitouran @xingjianz , thanks for reporting the issues with rich contexts/information.

The first issue is resolved with 95cde5a. 

For the second issue in (2), It seems wrong weights are fed to the `donut-python`. The error seems to pop up when model weights and an initialized `donut-python` model architecture did not match.
To be specific, for @leitouran , I recommend seeing these release notes at https://github.com/clovaai/donut/releases/tag/1.0.5. Cloning from the `official` branch would fix the issue. 

Hope this helps. Please let me know if you are still confused. Feel free to reopen this or open another issue if you have anything new for sharing and debugging :)

**Comment by leitouran** [comment]
Hi @gwkrsrch, thank you for your answer. Just had the chance of testing out what you suggested. Unfortunately the issue (2) persists. I've got the latest commit of the repo. Could it be that the donut-base I'm using was generated with another archtecture? I cloned it fresh from huggingface `(git clone https://huggingface.co/naver-clova-ix/donut-base`). 

Maybe my transformers version is off? I'm using the requirements provided in Donut repo, though. Any other ideas? Thank you very much in advance.

**Comment by gwkrsrch** [comment]
`git clone -b official --single-branch https://huggingface.co/naver-clova-ix/donut-base` will work :) Please give it a try and let me know if you still have this issue.

**Comment by leitouran** [comment]
Oh! The "official" branch was literally a branch named "official" haha. I'll try that out first thing tomorrow. Thank you @gwkrsrch!

**Comment by csanadpoda** [comment]
The issue persists with your pretrained models naver-clova-ix/donut-base-finetuned-cord-v1 and naver-clova-ix/donut-base-finetuned-cord-v2 even after installing trandformers==4.25.1

**Comment by getsanjeevdubey** [comment]
@gwkrsrch

**Comment by sudhitpanchal** [comment]
What's the problem with the "NotImplementedError: Make sure_init_weightsis implemented for <class 'donut.model.DonutModel'>"  I am getting too after solving too much dependencies of versions and files in the file from https://github.com/clovaai/donut/blob/master/train.py

**Comment by asfansajid123** [comment]
@gwkrsrch @csanadpoda 

I am trying to load the pretrained model naver-clova-ix/donut-base-finetuned-cord-v2 but getting the same error every time:
Make sure _init_weights is implemented for <class 'donut.model.DonutModel'>"

P.s: I have already tried by cloning the official branch of the repo via huggingface.co

Can you elaborate why this error is persisting or what could have gotten wrong in cloning the official branch? Your input would really mean a lot.

![image](https://github.com/clovaai/donut/assets/135522998/493c5fcb-1565-4fd6-adff-e422395b9441)

**Comment by sudhitpanchal** [comment]
> @gwkrsrch @csanadpoda
> 
> I am trying to load the pretrained model naver-clova-ix/donut-base-finetuned-cord-v2 but getting the same error every time: Make sure _init_weights is implemented for <class 'donut.model.DonutModel'>"
> 
> P.s: I have already tried by cloning the official branch of the repo via huggingface.co
> 
> Can you elaborate why this error is persisting or what could have gotten wrong in cloning the official branch? Your input would really mean a lot.
> 
> ![image](https://user-images.githubusercontent.com/135522998/263935963-493c5fcb-1565-4fd6-adff-e422395b9441.png)

I reimplemented everything and it worked great now!

**Comment by pandadom** [comment]
_init_weights raise NotImplementedError   --> usually indicates that the inference script is using a different versions of the transformers library as the training script!
