### ISSUE TITLE
donut processing on PDF Documents

### ISSUE THREAD

**Issue by Arun4GS** [clovaai/donut#30]
Hello,

I have few certificate documents which are in a PDF format.  I  want to extract metadata on those documents as suggested by you .
Could you please clarify me on the below points.

1.Can I use your model directly without pretraining on the certificate data.
2. How to train your model on my certificates as it is confidential  and what folder structure are you expecting to train the data.
3. How do I convert my dataset into your format (synthdog) – It was not much clear to me.

Thank you and looking forward to your response.

Best Regards,
Arun

**Comment by Arun4GS** [comment]
Awaiting your response!

**Comment by gwkrsrch** [comment]
Hi, let me get a brief answer first. For (1), it depends on the data/task (If the data/task share similar characteristics, you may use the pre-trained model directly). But generally, yes, the model needs to be fine-tuned. For (2) and (3), the README (https://github.com/clovaai/donut/blob/master/README.md) and tutorial at [this link](https://towardsdatascience.com/ocr-free-document-understanding-with-donut-1acfbdf099be) might be helpful to you. The folder structure is explained at https://github.com/clovaai/donut#data. Hope this helps. Please let me know if you are still confused.

Kind Regards,
Geewook Kim

**Comment by Arun4GS** [comment]
Thank you for your response Kim. Have some clarity now. I will check the files you mentioned above and will reach back if I have any issue. 
Best Regards,
Arun

**Comment by gwkrsrch** [comment]
Close this issue since the original questions are answered. Feel free to reopen this or open another issue if you have anything new for sharing :)
