### ISSUE TITLE
How to improve OCR accuracy for Japanese characters?

### ISSUE THREAD

**Issue by kirby707** [clovaai/donut#305]
During some experiments, I noticed that sometimes Japanese characters are not correctly recognized. Not necessarily very complex characters, but simple and commonplace characters such as 津 gets recognized as 活 etc.

My understanding is that it is related to the pre-training task but I'm not sure how to solve the issue. Just for ideas:

1. Is it possible to additionally pre-train the "donut-base" model for improved OCR accuracy?
2. Is it possible to swap the Swin Transformer for something else that provide better results?

If anyone has any ideas/hints/suggestions related to OCR accuracy, it will be very much appreciated!

**Comment by bliujunyuan** [comment]
Maybe the pre-train model Japanese data  distribution infected by other language dataset.The additionally training may work.

**Comment by kirby707** [comment]
Thank you for the comment!
It is a possibility... If I get some opportunity in the future, I will give it a try.
