### ISSUE TITLE
Fine Tuning  with  Arabic 

### ISSUE THREAD

**Issue by Mahmuod1** [clovaai/donut#33]
First I would to thank you for this repo 
i want to work in Arabic lang and Arabic lang and the Arabic Lang  is RTL 
could you tell me a pref to the changes i would make when adding the Arabic Lang in the SynthDoG to create the Arabic dataset
and in the model creation

**Comment by Mahmuod1** [comment]
@gwkrsrch please any help

**Comment by gwkrsrch** [comment]
Hi @Mahmuod1 , there are several options you can take. You may modify the layout/textbox generation module to make the desired RTL layout. There would be several code lines to modify, e.g., [textbox](https://github.com/clovaai/donut/blob/8f2d51530835f7c412ee8c5c1da490ea0e449b18/synthdog/elements/textbox.py#L10-L43), [layouts](https://github.com/clovaai/donut/tree/8f2d51530835f7c412ee8c5c1da490ea0e449b18/synthdog/layouts).
Another option is to generate the data with your own code based on SynthDoG. The followings are the main flow of the preliminary version of SynthDoG. The first step is to draw texts on a paper texture image. The following links would also be helpful to you.
- https://www.blog.pythonlibrary.org/2021/02/02/drawing-text-on-images-with-pillow-and-python
- https://stackoverflow.com/a/50189559

And then, using a perspective transformation (or other transformations), you can embed the synthetic paper into a background. Although the idea is simple, you will see some agreeable results. You may further enhance the quality of the generated samples via various techniques, but it is optional. Hope this helps :) Feel free to reopen this or open another issue if you have anything new for sharing.

**Comment by Mahmuod1** [comment]
thanks, @gwkrsrch for your detailed instructions 
can you please give me instructions for the donut model configuration that will be changed as it language specific 
I will use the document parsing training so please can you tell me what should care about the training configurations

**Comment by BakingBrains** [comment]
@Mahmuod1 Were you able to finetune on new language?

**Comment by akashlp27** [comment]
Hi, @mahmuod1, @gwkrsrch were you able to generate images using synthdog for RTL languages such as arabic.... any suggestions will help a lot..

**Comment by mirrorboat** [comment]
@akashlp27  Did you generate  arabic images successfully ? Thanks for your help in advance.

**Comment by mohamedsaeed8223** [comment]
I managed to render Arabic text correctly by modifying the code for Synthtiger 

find your installed synthtiger and go to the file `synthtiger/layers/text_layer.py` 
you will find the `draw.text()` at L158
you can do a quick hack around and add these 2 lines before the functions call

`
text = arabic_reshaper.reshape(text)
text = get_display(text)
`

and your arabic text will be renderd correctly, of course it would be much better if you made it as a flag passed in the config file if true then reshape string

**Comment by mlcom** [comment]
we were able to generate images and dataset for donut model on arabic and persian language using this repository 
[Synthdog-RTL](https://github.com/aiviewz/Synthdog-RTL)
complete article which helped me is following
[How To Create Synthetic Dataset for Donut OCR for your custom language?](https://www.aiviewz.com/posts/how-to-create-synthetic-dataset-for-donut-ocr-for-your-custom-language)
