### ISSUE TITLE
Performance with CPU

### ISSUE THREAD

**Issue by maycuatroi** [clovaai/donut#35]
I notice you put the model on the Gradio demo, and it seems to be running nicely. However, when I attempt to "dockerize" the model and run it in the cloud with the following configuration: 4 vCPU and 16GB RAM, it remains frozen or extremely sluggish (5 minutes per picture).

Could you please give the infrared configuration on the Gradio demo? Is there anything I did wrong?

**Comment by maycuatroi** [comment]
I try to modify the model structure to the same configuration as the cord-v2 public model on the Hugging face. 
However, CPU run time still costs between 20 and 60 seconds. I tested it on Docker images with four Intel Core i7 7700k vCPUs and the Amazon EC2 environment: 4 vCPUs and 16 GB RAM.
I believe the issue stems from my vocabulary and the complexity of my prediction scenario. I'm working with menu image data and Vietnamese.

**Comment by mjohar4** [comment]
I ran the [DocVQA Task1](https://rrc.cvc.uab.es/?ch=17) model locally(CPU) and tested it on Hagging Face demo. In both cases, the result took around 90 sec per question.
