### ISSUE TITLE
How to get confidence score for predictions?

### ISSUE THREAD

**Issue by SamSamhuns** [clovaai/donut#37]
Hi, thank you for this outstanding work. Could you point me to how one could generate confidence scores along with the JSON predictions from the models, especially the models for the Document Parsing Task?

Thanks

**Comment by logan-markewich** [comment]
I've looked into generating confidence, but it's not really useful. 

Since the output is coming from BART, the confidence is just the confidence of each token generated, multiplied together. 

However, when I tried doing this, my confidences were always extremely high. It's not as helpful as you would think

**Comment by SamSamhuns** [comment]
I did manage to get the scores for the JSON predictions. It does seem like a lot of the confidence scores are high but I have seen some that are low, but I get that the BART decoder generates new tokens based on the previous output token.

**Comment by daivikbhatia** [comment]
Hi @SamSamhuns , Can you please share how did you manage to get scores for json predictions?

**Comment by logan-markewich** [comment]
@daivikbhatia here's how I did it (line 645 in donut/model.py). Add the "return_scores" argument and then use those to calculate the total score:
```
# get decoder output
  decoder_output = self.decoder.model.generate(
      decoder_input_ids=prompt_tensors,
      encoder_outputs=encoder_outputs,
      max_length=self.config.max_length,
      early_stopping=True,
      pad_token_id=self.decoder.tokenizer.pad_token_id,
      eos_token_id=self.decoder.tokenizer.eos_token_id,
      use_cache=True,
      num_beams=1,
      bad_words_ids=[[self.decoder.tokenizer.unk_token_id]],
      return_dict_in_generate=True,
      output_attentions=return_attentions,
      output_scores=True
  )

  # calcuate confidences
  gen_sequences = decoder_output.sequences[:, prompt_tensors.shape[-1]:-1]
  probs = torch.stack(decoder_output.scores, dim=1).softmax(-1)
  gen_probs = torch.gather(probs, 2, gen_sequences[:, :, None]).squeeze(-1)
  unique_prob_per_sequence = gen_probs.prod(-1)

  output = {"predictions": list(), "confidences": unique_prob_per_sequence}
  for seq in self.decoder.tokenizer.batch_decode(decoder_output.sequences):
      seq = seq.replace(self.decoder.tokenizer.eos_token, "").replace(self.decoder.tokenizer.pad_token, "")
      seq = re.sub(r"<.*?>", "", seq, count=1).strip()  # remove first task start token
      if return_json:
          output["predictions"].append(self.token2json(seq))
      else:
          output["predictions"].append(seq)
```

**Comment by SamSamhuns** [comment]
You'd still need to match the confidences to the final JSON predictions for each field though. I've done a rough re-write of the `token2json` function to achieve this along with a lot of other monkey-patching. I'll attach my `donut/model.py` here if anyone wants a reference in the future or the check the validity of the confidence generation.

[model.py.zip](https://github.com/clovaai/donut/files/9488876/model.py.zip)

**Comment by BakingBrains** [comment]
Can we get Entity confidence (For parser).

For Example, how confident that the given value is total_price?

```
total_price:  "120,000"
```
Any suggestions?

Thanks and Regards
