### ISSUE TITLE
Input size parameter clarification

### ISSUE THREAD

**Issue by leitouran** [clovaai/donut#39]
I'm trying to run my own fine-tunning for document parsing. When building the train configuration I wondered: Is the input_size parameter related to the the size of the images in the dataset or is it only used for the Swin transfomer to create the embedding windows?

In case it's the second. When should it be customized and what constraints apply to the values provided?

Thank you!

**Comment by maycuatroi** [comment]
The image size is equal to the image input size. The image will be resized to this size.

In config (*.yaml) format, the image size is [width, height].

**Comment by leitouran** [comment]
Thank you @maycuatroi

**Comment by VictorAtPL** [comment]
@leitouran @maycuatroi 

> In config (*.yaml) format, the image size is [width, height].

It's actually the opposite (despite that docs say that). It's `[height, width]`.

Source of truth: https://github.com/clovaai/donut/blob/4cfcf972560e1a0f26eb3e294c8fc88a0d336626/donut/model.py#L120
