### ISSUE TITLE
linux or windows ?

### ISSUE THREAD

**Issue by trikiamine23** [clovaai/donut#41]
can we run the train script on windows ?

**Comment by maycuatroi** [comment]
The train script works on both Linux and Windows. If you are struggling, please describe it in the issue.

**Comment by trikiamine23** [comment]
All good I think, I was trying to make it work on windows, but I didn't see that by default it was used in multiGPU
I changed parameters and it worked just fine.
thank you

**Comment by cavidhabibov** [comment]
> All good I think, I was trying to make it work on windows, but I didn't see that by default it was used in multiGPU I changed parameters and it worked just fine. thank you

@trikiamine23 , can you please explain me what parameters did you change and how did you handle ""RuntimeError: Distributed package doesn't have NCCL built in" on Windows?

**Comment by jackkwok** [comment]
@cavidhabibov , you just need to comment out one line in `train.py`:

# strategy="ddp",

ddp stands for "distributed data parallel" which depends on Nvidia NCCL.
