### ISSUE TITLE
Performance gap of baseline methods

### ISSUE THREAD

**Issue by zx1239856** [clovaai/donut#42]
Thanks for the inspiring work. When I checked the Table 2 in the main paper, I noticed the field-level F1 scores for baseline methods, such as LayoutLM, LayoutLMv2, and BROS are much lower than those in their papers. They have 90+ F1 score on CORD whereas in your paper they score ~80. Could you please provide an explanation?
<img width="774" alt="image" src="https://user-images.githubusercontent.com/4181375/188012896-c8512403-6d15-4c0a-915c-0650b49c2857.png">

### Table from LayoutLMv2 paper
<img width="709" alt="image" src="https://user-images.githubusercontent.com/4181375/188013250-c6c27a3e-3afc-4328-8470-3a34e150c390.png">

**Comment by gwkrsrch** [comment]
Hi @zx1239856 , 

the experimental setting is different. This gap comes from whether the models use the GT OCR or not.

We consider an end-to-end setting. If a single character is missed in the OCR, there is no chance for the conventional tagging-based models. Plus, the current test script is the most strict version, which might be too severe for all methods in an end-to-end setting regardless of the OCR dependency. 
Similar results/trends can also be seen in some recent works, e.g., https://arxiv.org/abs/2005.13118 or https://arxiv.org/abs/2203.16618. Table4 of https://arxiv.org/abs/2005.13118 shows ~83 SROIE F1 scores in the E2E setting and 90+ scores in the GT OCR setting. Hope this helps :)
