### ISSUE TITLE
Using base model to OCR text

### ISSUE THREAD

**Issue by alexmt-scale** [clovaai/donut#44]
Hello,
Given it seems that the pretraining method that was used consists in asking DONUT to OCR the text, I was wondering if it was possible to use the pretrain model (https://huggingface.co/naver-clova-ix/donut-base) for OCR. If so, what prompt can we use to do that? And is there anything else that needs to be done? 

Btw, this is amazing work, congratulations! :)

**Comment by alexmt-scale** [comment]
It seems that using <s_iitcdip> as the initial task_prompt actually does the trick!

**Comment by jackkwok** [comment]
Does this imply `donut-base` was pre-trained on IIT-CDIP dataset (https://data.nist.gov/od/id/mds2-2531) along with SyncDog synthetic dataset ?

I am trying to understand what dataset(s) were used in pretraining/training `donut-base`.

**Comment by BSharp94** [comment]
@alex-matton Can you give an example of how you did this?

I tried to input "<s_iitcdip>" as my text prompt input but received a weird response:

{'text_sequence': '<pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad> '}
