### ISSUE TITLE
Finetuning Epochs on DocVQA and RVLCDIP

### ISSUE THREAD

**Issue by Veason-silverbullet** [clovaai/donut#49]
Hi, @SamSamhuns @gwkrsrch . Many thanks for your efforts!

I tried finetuning DONUT on RVLCDIP and DocVQA with 8 V100 GPUs, but the finetuning process is too long (up to weeks for RVLCDIP). May I know if the epochs of 100 for RVLCDIP and 300 for DocVQA are necessary and how you finetune the model (e.g., epoch and batch size)? The finetuning overhead is too large with such long epochs according to the provided configs.

**Comment by logan-markewich** [comment]
pretty sure those are "max" epochs, early stopping should stop the run much sooner.
