### ISSUE TITLE
Dataset for pre-training 

### ISSUE THREAD

**Issue by hardik2396** [clovaai/donut#5]
First of all, thank you for open-sourcing codebase and pre-trained models for tinkering. I am really excited to try new ideas to extend the project. Specifically, I want to train the model in a slightly different way. As mentioned in section 3.4, Clova-based results are awe-inspiring compared to others. I will be happy if you can share preprocessed dataset for training purposes.:)

**Comment by eleventh83** [comment]
Unfortunately, the dataset inferred by Clova OCR seems to be difficult to share. In the case of products using the internal API, it is prohibited to take them out due to internal regulations.

**Comment by gwkrsrch** [comment]
For your experiment, I think you can use the APIs / open-source libraries introduced in Appendix A.1 (https://arxiv.org/abs/2111.15664). As mentioned in the manuscript, the CLOVA engine showed robust performance for documents, such as receipts. But, the other engines also performed well for general English documents. 
I hope this answer is helpful to you :) Please let me know if you are still confused.
