### ISSUE TITLE
How to use Donut Model encoders as embeddings?

### ISSUE THREAD

**Issue by atharvjairath** [clovaai/donut#51]
Hi,
First of all amazing work!
I wanted to use pre-trained donut model to generate embeddings for my documents, is there any easy way to do?
or I would need to make some changes in forward function?
Thank you!

**Comment by SamSamhuns** [comment]
Just use the `last_hidden_state` from inside the `inference` call of the Donut model inside `donut/model.py`.  These are the Document Image embeddings from the Swim Transformer encoder.

```python
454        last_hidden_state = self.encoder(image_tensors)
455        if self.device.type != "cuda":
456           last_hidden_state = last_hidden_state.to(torch.float32)
```

**Comment by atharvjairath** [comment]
Thanks! used this only
