### ISSUE TITLE
RuntimeError: output shape [1,1280, 960] does not match with the broad cast shape [3,1280,960]

### ISSUE THREAD

**Issue by moni-learn010** [clovaai/donut#6]
Hello, I was trying to run the Donut model for SROIE data for KIE task. While training, it gives the this **runtime error: output shape [1,1280, 960] does not match with the broad cast shape [3,1280,960]**. Can anyone please help me out how to resolve this issue?

**Comment by gwkrsrch** [comment]
Hi, thank you for the report. [This fix](https://github.com/clovaai/donut/commit/74507ce85deed77807f343ac75c243663b2db691) would probably solve the issue. Please let me know if there is any issues :)

**Comment by moni-learn010** [comment]
Thanks for your quick response. Yes, the issue is resolved. Appreciate it
