### ISSUE TITLE
Inference problem output

### ISSUE THREAD

**Issue by trikiamine23** [clovaai/donut#60]
I have a problem using, on another usecase, the inference script used in this tutorial https://towardsdatascience.com/ocr-free-document-understanding-with-donut-1acfbdf099be

`image = Image.open("./donut/misc/sample_image_cord_test_receipt_00004.png").convert("RGB")`
`output = model.inference(image=image, prompt="<s_cord-v2>")`

what am I suppose to put in prompt argument ?
I noticed that output depends on the prompt.

Thank you

**Comment by vishal-nayak1** [comment]
@trikiamine23 try replacing prompt "<s_cord-v2>" with your dataset folder name "<s_dataset_directory_name>".

**Comment by trikiamine23** [comment]
thank you it worked just fine
