### ISSUE TITLE
How to do pre-training?

### ISSUE THREAD

**Issue by daeing** [clovaai/donut#61]
I noticed that the way of pre-training is to use mask language modeling in your article. Is there any plan to expose this part of the code? Or is there any relevant code to refer to?

**Comment by gwkrsrch** [comment]
Hi, There is some misunderstanding here. The manuscript proposes a simple text-reading task as a pre-training task, not mask language modeling, and the code is available. The followings would be helpful to you. Hope this helps :)
- https://github.com/clovaai/donut#for-psuedo-text-reading-task
- https://github.com/clovaai/donut#training

**Comment by moyans** [comment]
hi，no config for "for-psuedo-text-reading-task" found，any plan to release?
