### ISSUE TITLE
inference speed is very slow on cpu for docvqa task and CUDA out of memory

### ISSUE THREAD

**Issue by roburst2** [clovaai/donut#63]
it is taking almost 300 sec for single question on CPU

on gpu i am getting cuda out of memory
below are the configuration

NVIDIA GeForce RTX 2080 Ti
memory 11264 MiB

**Comment by gwkrsrch** [comment]
Hi, I recently updated some lines to make the CPU inference fast. It seems torch.bfloat16-related lines were the source of the issue. Please use the latest version. 

For the memory issue, #28 and #70 would be helpful to you.

Feel free to reopen this or open another issue if you have anything new for sharing/debugging.
