### ISSUE TITLE
Release yaml files

### ISSUE THREAD

**Issue by rtanaka-lab** [clovaai/donut#7]
Hi,

Thank you for sharing your interesting work. I was wondering if there is an expected date on when you will be releasing yaml files regarding anything other than CORD? I want to reproduce the experimental results in my environment.

**Comment by gwkrsrch** [comment]
Hi, thank you for your interest. We will update it, but let me get a quick answer first. 
The trained model configurations (e.g., input resolution, max_length, etc) are currently available at `config.json`; for example, see [docvqa model's configuration](https://huggingface.co/naver-clova-ix/donut-base-finetuned-docvqa/blob/main/config.json). Plus, more details of important setups are also available at Appendix A.5 (https://arxiv.org/abs/2111.15664). 
I will notify you when the update is done :)

**Comment by gwkrsrch** [comment]
Hi @rtanaka-lab, the files are updated in 3c6d818. Hope this helps :)
