### ISSUE TITLE
Handling missing values own training jsonl file

### ISSUE THREAD

**Issue by jpaublant** [clovaai/donut#86]
Hi, 
I'm currently working with your model while training with my own dataset.

I was wondering if you have a advice on how to handle missing values in the 'jsonl' files.

So far, I'm using the structure: "\<key>\": "\"\

**Comment by gwkrsrch** [comment]
Hi, this issue seems same as #82. Hope this help.  Please let me know if you are still confused. 
Feel free to reopen this or open another issue if you have anything new for sharing and debugging :)
