### ISSUE TITLE
German Language Decoder

### ISSUE THREAD

**Issue by ArlindNocaj** [clovaai/donut#91]
Hi all,

First of all, thanks a lot for the great work with Donut. I think its revolutionary, people are just not getting it fully yet 😀 

I have German tokens and want to limit the decoder to German tokens outcomes only. Any suggestion on the Decoder which I can use? Can you provide some hints/snippets on how to do that? 

Thanks a lot for any hints.

**Comment by gwkrsrch** [comment]
Hi, thank you for your interest on our work :)
The current implementation use the vocabulary of `asian-bart-ecjk` by default.
I've just checked that german alphabets (A~Z and Ä, Ö, Ü, ß) are in the vocabulary.
If you want to limit the decoder vocabulary, #78 might be helpful to you. 
Hope this help. Please let me know if you are still confused.
