### ISSUE TITLE
No module named 'datasets

### ISSUE THREAD

**Issue by laiqirong** [clovaai/donut#98]
in util.py ,from datasets import load_dataset,but there is no this file

**Comment by gwkrsrch** [comment]
Hi @laiqirong , It seems that a library, [`datasets`](https://huggingface.co/docs/datasets/image_dataset), is not installed.

Here are some references for you:
- https://github.com/clovaai/donut/blob/1.0.9/setup.py#L55
- https://huggingface.co/docs/datasets/image_dataset

Hope this helps :)
